# What Python version is installed where:
# https://www.appveyor.com/docs/build-environment/#python

image:
  - Visual Studio 2019
  - Ubuntu
  - macos

environment:
  matrix:
  - TOXENV: python3.7
  - TOXENV: python3.8
  - TOXENV: python3.9
  - TOXENV: python3.10
  - TOXENV: python3.11

build: false

install:
  # - py --list
  # - py -m pip install --upgrade pip
  - python -m pip install tox

test_script:
  - python -m tox
