site_name: pytest-sqlfluff
site_description: A pytest plugin to use sqlfluff to enable format checking of sql files
site_author: Paul Sutherland

theme: readthedocs

repo_url: https://github.com/prsutherland/pytest-sqlfluff

pages:
- Home: index.md
